apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapi
spec:
  selector:
    matchLabels:
      app: taskapi
  template:
    metadata:
      labels:
        app: taskapi
    spec:
      containers:
      - name: taskapi
        image: pyaephoaungsimtech/taskapi:1.0.0 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taskapiservice
  annotations:
   konghq.com/plugins: twelve-per-min

spec:
  type: NodePort
  selector:
    app: taskapi
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31555

